<a href="https://colab.research.google.com/github/jejee777/RAG-systems/blob/main/dL_project_firstAid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import os

os.listdir('/content')

['.config', 'merged_data.csv', 'sample_data']

In [ ]:
df = pd.read_csv('/content/merged_data.csv')

print(df.head())
print(df.columns)
print(df.shape)
print(df.isnull().sum())

   Unnamed: 0                                           question  \
0           0       What to do if someone has a cardicac arrest?
1           1     My friend is injured and bleeding, what to do?
2           2                                  what is chocking?
3           3                 what to do is someone is chocking?
4           4  For someone who is obese or pregnant, how to h...

                                              answer
0   If you think someone is in cardiac arrest, th...
1  \n    Put on disposable gloves if you have the...
2  Choking happens when a person’s windpipe (trac...
3  \n    Stand behind the person and lean them sl...
4  perform the thrusts around the chest instead o...
Index(['Unnamed: 0', 'question', 'answer'], dtype='object')
(346, 3)
Unnamed: 0    0
question      1
answer        1
dtype: int64

In [ ]:
print(df.columns)
print(df.head())

Index(['Unnamed: 0', 'question', 'answer'], dtype='object')
   Unnamed: 0                                           question  \
0           0       What to do if someone has a cardicac arrest?
1           1     My friend is injured and bleeding, what to do?
2           2                                  what is chocking?
3           3                 what to do is someone is chocking?
4           4  For someone who is obese or pregnant, how to h...

                                              answer
0   If you think someone is in cardiac arrest, th...
1  \n    Put on disposable gloves if you have the...
2  Choking happens when a person’s windpipe (trac...
3  \n    Stand behind the person and lean them sl...
4  perform the thrusts around the chest instead o...

In [ ]:
# Remove unnecessary column
df = df.drop(columns=['Unnamed: 0'])

# Remove missing values
df = df.dropna()

# Create document list
documents = []

for i, row in df.iterrows():
    text = f"Question: {row['question']}\nAnswer: {row['answer']}"
    documents.append(text)

# Display first document
print(documents[0])

# Display total number of documents
print("\nTotal documents:", len(documents))

Question: What to do if someone has a cardicac arrest?
Answer:  If you think someone is in cardiac arrest, there are four steps you can take to help them.
    Find a person nearby. Make eye contact, point to them, and say: “Call 911.”
    Start doing chest compressions on the person who needs help. Using both your hands, push down hard and fast in the center of the person’s chest. Let their chest come back up naturally between compressions. You may hear pops or snaps; this is normal.
    Keep going until someone with more training arrives.
    If you’re trained in CPR, you can use chest compressions and rescue breathing.
    If it’s available, use an AED. However, do not put off doing chest compressions to go look for an AED. If possible, instruct someone else to go find the device and bring it to you.

Total documents: 345

In [ ]:
# Install sentence-transformers
!pip install sentence-transformers

# Import model
from sentence_transformers import SentenceTransformer

# Load embedding model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

# Generate embeddings
embeddings = embedding_model.encode(documents)

# Check embedding shape
print("Number of embeddings:", len(embeddings))
print("Embedding vector size:", len(embeddings[0]))

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Number of embeddings: 345
Embedding vector size: 384

In [ ]:
# Install ChromaDB
!pip install chromadb

import chromadb

# Create Chroma client
client = chromadb.Client()

# Create collection
collection = client.create_collection(name="first_aid_collection")

# Add documents and embeddings
for i, doc in enumerate(documents):
    collection.add(
        documents=[doc],
        embeddings=[embeddings[i].tolist()],
        ids=[str(i)]
    )

print("Documents stored successfully!")

Requirement already satisfied: chromadb in /usr/local/lib/python3.12/dist-packages (1.5.9)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.5.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.14.0)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.46.0)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.0.2)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.26.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.41.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.41.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.41.1)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.80.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.2)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (35.0.0)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.8)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.1)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.4)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.74.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.41.1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.41.1)
Requirement already satisfied: opentelemetry-proto==1.41.1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.41.1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.62b1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.62b1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.20.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb) (1.11.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.4.3)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.7)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Documents stored successfully!

In [ ]:
# User query
query = "What should I do if someone is choking?"

# Convert query to embedding
query_embedding = embedding_model.encode([query])[0]

# Retrieve similar documents
results = collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=3
)

# Display retrieved documents
for doc in results['documents'][0]:
    print(doc)
    print("\n------------------\n")

Question: ["How to treat Choking?", "What to do for Choking?", "First aid for Choking?", "How to manage Choking?", "Choking"]
Answer: ["Perform the Heimlich maneuver if the person cannot speak, cough, or breathe. Stand behind the person and wrap your arms around their waist. Make a fist with one hand and place it just above the navel. Grasp your fist with the other hand and perform quick, upward thrusts. Seek medical help if the person does not recover quickly."]

------------------

Question: ["How to treat Choking?", "What to do if someone is Choking?", "Choking first aid", "Steps to help Choking person", "Choking"]
Answer: ["Perform the Heimlich maneuver by standing behind the person and giving abdominal thrusts. If the person is unconscious, perform CPR and call for emergency help. Encourage the person to cough if they can. Avoid giving the person anything to eat or drink."]

------------------

Question: How to know if someone is chocking
Answer: Signs of choking include:
 Coughing, either forcefully or weakly
 Clutching the throat with one or both hands
Inability to cough, speak, cry or breathe
 Making high-pitched noises while inhaling or noisy breathing
 Panic
 Bluish skin colour
 Sometimes, the person may cough weakly or make high-pitched noises, which indicates he
or she is not getting enough air to stay alive.

------------------

### ***Gemini***

In [ ]:
!pip install google-generativeai

Requirement already satisfied: google-generativeai in /usr/local/lib/python3.12/dist-packages (0.8.6)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.30.3)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.194.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.47.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (5.29.6)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.12.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (4.67.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (4.15.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.27.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core->google-generativeai) (1.74.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core->google-generativeai) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (0.31.2)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (0.3.1)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->google-generativeai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->google-generativeai) (0.4.2)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.80.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.3.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2026.4.22)

In [ ]:
import google.generativeai as genai

genai.configure(api_key="AIzaSyDIPURQucixXTCOp0Y8wcDKK58yDCclDZM")

for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(m.name)

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3.1-flash-lite
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/gemini-3.1-flash-tts-preview
models/gemini-robotics-er-1.5-preview
models/gemini-robotics-er-1.6-preview
models/gemini-2.5-computer-use-preview-10-2025
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025

In [ ]:
import google.generativeai as genai

# Configure API key
genai.configure(api_key="AIzaSyDsyHmoPE3YLjLhgTMoW89IaCCVbBRparM")

# Load Gemini model
model = genai.GenerativeModel("models/gemini-2.5-flash")

print("Gemini loaded successfully!")

Gemini loaded successfully!

In [ ]:
# User question
query = "What should I do if someone is choking?"

# Convert query to embedding
query_embedding = embedding_model.encode([query])[0]

# Retrieve related documents
results = collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=3
)

# Extract retrieved documents
retrieved_docs = results['documents'][0]

# Combine retrieved documents into one context
context = "\n\n".join(retrieved_docs)

# Create prompt
prompt = f"""
You are a helpful first aid assistant.

Answer the user's question ONLY using the retrieved context below.

Retrieved Context:
{context}

User Question:
{query}
"""

# Generate response
response = model.generate_content(prompt)

# Print final response
print(response.text)

If someone is choking:
*   Perform the Heimlich maneuver if the person cannot speak, cough, or breathe.
*   To perform the Heimlich maneuver: Stand behind the person and wrap your arms around their waist. Make a fist with one hand and place it just above the navel. Grasp your fist with the other hand and perform quick, upward thrusts.
*   If the person is unconscious, perform CPR and call for emergency help.
*   Encourage the person to cough if they can.
*   Avoid giving the person anything to eat or drink.
*   Seek medical help if the person does not recover quickly.

In [ ]:
#another prompt

# User question
query = "What should I do if someone is choking?"

# Convert query to embedding
query_embedding = embedding_model.encode([query])[0]

# Retrieve related documents
results = collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=3
)

# Extract retrieved documents
retrieved_docs = results['documents'][0]

# Combine retrieved documents into one context
context = "\n\n".join(retrieved_docs)

# Create improved prompt
# Create improved prompt
prompt = f"""
You are a helpful AI first-aid assistant.

Use ONLY the retrieved context below to answer the user's question.

Provide:
- Clear first-aid steps
- A short and concise answer
- Safety advice when necessary
- Remind the user to contact emergency services in serious situations

Retrieved Context:
{context}

User Question:
{query}
"""

# Generate response
response = model.generate_content(prompt)

# Print final response
print(response.text)

Here are the first-aid steps for choking:

1.  **Encourage coughing:** If the person can cough, encourage them to do so.
2.  **Perform Heimlich maneuver:** If the person cannot speak, cough, or breathe, perform the Heimlich maneuver:
    *   Stand behind the person and wrap your arms around their waist.
    *   Make a fist with one hand and place it just above the navel.
    *   Grasp your fist with the other hand and perform quick, upward thrusts.
3.  **If unconscious:** If the person is unconscious, perform CPR and call for emergency help.

**Safety Advice:**
*   Avoid giving the person anything to eat or drink.

**Emergency Services:**
*   Seek medical help if the person does not recover quickly.
*   Always contact emergency services in serious situations.

**dynamic** **query**

to explain more the process

In [ ]:
# User question
query = input("Enter your first-aid question: ")

# Convert query to embedding
query_embedding = embedding_model.encode([query])[0]

# Retrieve related documents
results = collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=3
)

# Extract retrieved documents
retrieved_docs = results['documents'][0]

# Combine retrieved documents into one context
context = "\n\n".join(retrieved_docs)

# Create improved prompt
prompt = f"""
You are a helpful AI first-aid assistant.

Use ONLY the retrieved context below to answer the user's question.

Provide:
- Clear first-aid steps
- A short and concise answer
- Safety advice when necessary
- Remind the user to contact emergency services in serious situations

Retrieved Context:
{context}

User Question:
{query}
"""

# Generate response
response = model.generate_content(prompt)

# Print retrieved context
print("Retrieved Context:")
print(context)

print("\n====================\n")

# Print final response
print("Final Answer:")
print(response.text)

Enter your first-aid question: What should I do if someone is fainting?
Retrieved Context:
Question: ["How to treat Fainting?", "What to do for Fainting?", "First aid for Fainting?", "How to revive someone from Fainting?", "Fainting"]
Answer: ["Lay the person flat on their back and elevate their legs. Loosen any tight clothing. Ensure they have plenty of fresh air. If they do not regain consciousness within a minute, seek medical help. Monitor their condition until help arrives."]

Question: "My friend has been out in the sun all day and now they're confused and not sweating. What should I do?"
Answer: "Your friend might be suffering from heat stroke, a serious condition that requires immediate medical attention. Call emergency services right away. Move your friend to a cooler place and try to cool them down while waiting for help. Remove excess clothing and apply cool water to their skin. You can also place ice packs on their armpits, groin, neck, and back, where blood vessels are close to the surface. Do not give them anything to drink if they are unconscious or very confused."

Question: "What should I do after rescuing someone who was drowning but is now responsive?"
Answer:  "After rescuing a responsive person, keep them calm and warm. Check for any injuries and monitor their breathing and responsiveness. Encourage them to cough up any water they might have swallowed. Seek medical attention as soon as possible, as they might have inhaled water or suffered other injuries that aren’t immediately apparent."

====================

Final Answer:
If someone is fainting, follow these steps:

1.  Lay the person flat on their back.
2.  Elevate their legs.
3.  Loosen any tight clothing.
4.  Ensure they have plenty of fresh air.

**Safety Advice:** If they do not regain consciousness within a minute, seek medical help. Monitor their condition until help arrives.

what will apear to **user**

In [ ]:
# User question
query = input("Enter your first-aid question: ")

# Convert query to embedding
query_embedding = embedding_model.encode([query])[0]

# Retrieve related documents
results = collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=3
)

# Extract retrieved documents
retrieved_docs = results['documents'][0]

# Combine retrieved documents into one context
context = "\n\n".join(retrieved_docs)

# Create prompt
prompt = f"""
You are a helpful AI first-aid assistant.

Use ONLY the retrieved context below to answer the user's question.

Provide:
- Clear first-aid steps
- A short and concise answer
- Safety advice when necessary
- Remind the user to contact emergency services in serious situations

Retrieved Context:
{context}

User Question:
{query}
"""

# Generate response
response = model.generate_content(prompt)

# Display final response only
print("\nAI First-Aid Assistant:\n")
print(response.text)

Enter your first-aid question:     What should I do if someone has a burn?

AI First-Aid Assistant:

First, **stop the burning process**. This might involve turning off electricity, cleaning chemicals, or cooling heat with running water.

**For major burns, call 911 immediately.**

For burns that are not an emergency:
1.  **Flush** the burned area with cool running water for several minutes. Do not use ice.
2.  **Apply** a light gauze bandage. For minor burns, you can apply an ointment like aloe vera before covering.
3.  **Take** Motrin (ibuprofen) or Tylenol (acetaminophen) for pain if needed.
4.  **Do not break** any blisters that form.

**If it's an electrical burn:** Do not touch the person if they are still in contact with the electrical source. Turn off the power or use a non-conductive object to separate them. Once it is safe, call emergency services immediately.

Always contact emergency services in serious situations or for major burns.

# System Evaluation

In [ ]:
!pip install bert-score rouge-score

Requirement already satisfied: bert-score in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: rouge-score in /usr/local/lib/python3.12/dist-packages (0.1.2)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.10.0+cpu)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.2.2)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (5.0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (4.67.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert-score) (3.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bert-score) (26.1)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2026.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (1.11.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (3.3.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2026.4.22)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.24.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert-score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.1.2)

In [ ]:
import pandas as pd
import time
from bert_score import score
from rouge_score import rouge_scorer

test_cases = [
    {
        "Type": "In-dataset",
        "Query": "What should I do if someone is choking?",
        "Reference Answer": "Encourage coughing if the person can cough. If they cannot breathe, call emergency services and perform abdominal thrusts if trained."
    },
    {
        "Type": "In-dataset",
        "Query": "What should I do if someone has a burn?",
        "Reference Answer": "Cool the burn under running water, cover it with a clean dressing, do not use ice, and call emergency services for serious burns."
    },
    {
        "Type": "Out-of-dataset",
        "Query": "My friend fainted suddenly, what should I do?",
        "Reference Answer": "Lay the person down, raise their legs, check breathing, keep them safe, and call emergency services if they do not recover quickly."
    }
]

results_list = []

for case in test_cases:
    query = case["Query"]
    reference = case["Reference Answer"]

    start_time = time.time()

    # Convert query to embedding
    query_embedding = embedding_model.encode([query])[0]

    # Retrieve top-3 documents
    results = collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=3
    )

    retrieved_docs = results["documents"][0]
    context = "\n\n".join(retrieved_docs)

    # Generate answer
    prompt = f"""
You are a helpful AI first-aid assistant.

Use ONLY the retrieved context below to answer the user's question.

Provide:
- Clear first-aid steps
- Very concise answer
- Maximum 5 bullet points
- Safety advice when necessary

Retrieved Context:
{context}

User Question:
{query}
"""

    response = model.generate_content(prompt)
    generated_answer = response.text

    response_time = round(time.time() - start_time, 2)

    results_list.append({
        "Type": case["Type"],
        "Query": query,
        "Reference Answer": reference,
        "Generated Answer": generated_answer,
        "Response Time (sec)": response_time
    })

eval_df = pd.DataFrame(results_list)
eval_df

,Type,Query,Reference Answer,Generated Answer,Response Time (sec)
0,In-dataset,What should I do if someone is choking?,Encourage coughing if the person can cough. If...,Here are the steps to take if someone is choki...,4.33
1,In-dataset,What should I do if someone has a burn?,"Cool the burn under running water, cover it wi...",Here's what to do if someone has a burn:\n\n* ...,6.29
2,Out-of-dataset,"My friend fainted suddenly, what should I do?","Lay the person down, raise their legs, check b...",* Lay the person flat on their back.\n* El...,2.98

In [ ]:
references = eval_df["Reference Answer"].tolist()
candidates = eval_df["Generated Answer"].tolist()

P, R, F1 = score(
    candidates,
    references,
    lang="en",
    verbose=True
)

eval_df["BERTScore Precision"] = P.tolist()
eval_df["BERTScore Recall"] = R.tolist()
eval_df["BERTScore F1"] = F1.tolist()

eval_df

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
pooler.dense.weight             | MISSING    |
pooler.dense.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

calculating scores...
computing bert embedding.

  0%|          | 0/1 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/1 [00:00<?, ?it/s]

done in 13.35 seconds, 0.22 sentences/sec

,Type,Query,Reference Answer,Generated Answer,Response Time (sec),BERTScore Precision,BERTScore Recall,BERTScore F1
0,In-dataset,What should I do if someone is choking?,Encourage coughing if the person can cough. If...,Here are the steps to take if someone is choki...,4.33,0.831920,0.933565,0.879817
1,In-dataset,What should I do if someone has a burn?,"Cool the burn under running water, cover it wi...",Here's what to do if someone has a burn:\n\n* ...,6.29,0.809565,0.909641,0.856690
2,Out-of-dataset,"My friend fainted suddenly, what should I do?","Lay the person down, raise their legs, check b...",* Lay the person flat on their back.\n* El...,2.98,0.848956,0.916918,0.881629

In [ ]:
scorer = rouge_scorer.RougeScorer(
    ["rouge1", "rouge2", "rougeL"],
    use_stemmer=True
)

rouge1_scores = []
rouge2_scores = []
rougeL_scores = []

for ref, gen in zip(references, candidates):
    scores = scorer.score(ref, gen)
    rouge1_scores.append(scores["rouge1"].fmeasure)
    rouge2_scores.append(scores["rouge2"].fmeasure)
    rougeL_scores.append(scores["rougeL"].fmeasure)

eval_df["ROUGE-1"] = rouge1_scores
eval_df["ROUGE-2"] = rouge2_scores
eval_df["ROUGE-L"] = rougeL_scores

eval_df

,Type,Query,Reference Answer,Generated Answer,Response Time (sec),BERTScore Precision,BERTScore Recall,BERTScore F1,ROUGE-1,ROUGE-2,ROUGE-L
0,In-dataset,What should I do if someone is choking?,Encourage coughing if the person can cough. If...,Here are the steps to take if someone is choki...,4.33,0.831920,0.933565,0.879817,0.404762,0.195122,0.309524
1,In-dataset,What should I do if someone has a burn?,"Cool the burn under running water, cover it wi...",Here's what to do if someone has a burn:\n\n* ...,6.29,0.809565,0.909641,0.856690,0.217143,0.092486,0.125714
2,Out-of-dataset,"My friend fainted suddenly, what should I do?","Lay the person down, raise their legs, check b...",* Lay the person flat on their back.\n* El...,2.98,0.848956,0.916918,0.881629,0.333333,0.206897,0.333333

In [ ]:
summary_df = pd.DataFrame({
    "Metric": [
        "BERTScore Precision",
        "BERTScore Recall",
        "BERTScore F1",
        "ROUGE-1",
        "ROUGE-2",
        "ROUGE-L",
        "Average Response Time"
    ],
    "Score": [
        eval_df["BERTScore Precision"].mean(),
        eval_df["BERTScore Recall"].mean(),
        eval_df["BERTScore F1"].mean(),
        eval_df["ROUGE-1"].mean(),
        eval_df["ROUGE-2"].mean(),
        eval_df["ROUGE-L"].mean(),
        eval_df["Response Time (sec)"].mean()
    ]
})

summary_df

                  Metric     Score
0    BERTScore Precision  0.830147
1       BERTScore Recall  0.920041
2           BERTScore F1  0.872712
3                ROUGE-1  0.318413
4                ROUGE-2  0.164835
5                ROUGE-L  0.256190
6  Average Response Time  4.533333

#
# RAG System Evaluation on 10 Test Questions
#

In [ ]:
# =========================================================
# RAG SYSTEM EVALUATION - PART 1
# Generate Answers + Response Time
# =========================================================

import pandas as pd
import time

test_cases = [
    {
        "Type": "In-dataset",
        "Query": "What should I do if someone is choking?",
        "Reference Answer": "Encourage coughing if possible. If the person cannot breathe, call emergency services and perform abdominal thrusts if trained."
    },
    {
        "Type": "In-dataset",
        "Query": "What should I do if someone has a burn?",
        "Reference Answer": "Cool the burn with running water, cover it with a clean dressing, avoid ice, and seek emergency help for serious burns."
    },
    {
        "Type": "In-dataset",
        "Query": "How can I stop bleeding?",
        "Reference Answer": "Apply firm pressure with a clean cloth or bandage and seek emergency help if bleeding is severe or does not stop."
    },
    {
        "Type": "In-dataset",
        "Query": "How can I perform CPR?",
        "Reference Answer": "Call emergency services, start chest compressions hard and fast in the center of the chest, and use an AED if available."
    },
    {
        "Type": "In-dataset",
        "Query": "What should I do for a nosebleed?",
        "Reference Answer": "Sit upright, lean forward, pinch the soft part of the nose, and seek help if bleeding does not stop."
    },
    {
        "Type": "Out-of-dataset",
        "Query": "My friend fainted suddenly, what should I do?",
        "Reference Answer": "Lay the person down, raise their legs, check breathing, keep them safe, and call emergency services if they do not recover quickly."
    },
    {
        "Type": "Out-of-dataset",
        "Query": "A person is shaking and having a seizure, how can I help?",
        "Reference Answer": "Keep the person safe, move harmful objects away, do not restrain them, place them on their side when possible, and call emergency services if needed."
    },
    {
        "Type": "Out-of-dataset",
        "Query": "Someone is overheated and confused after being in the sun, what should I do?",
        "Reference Answer": "Move the person to a cool place, cool their body, give fluids if conscious, and call emergency services if symptoms are serious."
    },
    {
        "Type": "Out-of-dataset",
        "Query": "Someone twisted their ankle and it is swelling, what should I do?",
        "Reference Answer": "Rest the injured ankle, apply ice wrapped in cloth, compress it gently, elevate it, and seek medical help if pain or swelling is severe."
    },
    {
        "Type": "Out-of-dataset",
        "Query": "What should I do if someone may be having a heart attack?",
        "Reference Answer": "Call emergency services immediately, keep the person calm and resting, and begin CPR if they become unresponsive and are not breathing."
    }
]

def safe_generate(prompt, retries=3, wait_time=30):
    for attempt in range(retries):
        try:
            response = model.generate_content(prompt)
            return response.text
        except Exception:
            print(f"API error or rate limit. Attempt {attempt + 1}/{retries}")
            print("Waiting before retrying...")
            time.sleep(wait_time)

    return "ERROR: API generation failed."

results_list = []

for idx, case in enumerate(test_cases, start=1):
    print(f"Running test case {idx}/10...")

    query = case["Query"]
    reference = case["Reference Answer"]

    start_time = time.time()

    # Convert query to embedding
    query_embedding = embedding_model.encode([query])[0]

    # Retrieve top-3 relevant documents
    results = collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=3
    )

    retrieved_docs = results["documents"][0]
    context = "\n\n".join(retrieved_docs)

    # Create RAG prompt
    prompt = f"""
You are a professional first-aid assistant.

Answer ONLY using the retrieved context.

Instructions:
- Give concise first-aid steps
- Use bullet points
- Avoid repeating information
- Do not add unsupported medical advice
- Maximum 4 bullet points
- Keep the wording close to the retrieved context

Retrieved Context:
{context}

User Question:
{query}
"""

    generated_answer = safe_generate(prompt)

    response_time = round(time.time() - start_time, 2)

    results_list.append({
        "Question Type": case["Type"],
        "Query": query,
        "Reference Answer": reference,
        "Generated Answer": generated_answer,
        "Response Time (sec)": response_time
    })

    # Delay to reduce Gemini rate-limit errors
    time.sleep(25)

eval_df = pd.DataFrame(results_list)
eval_df

Running test case 1/10...
Running test case 2/10...
Running test case 3/10...
Running test case 4/10...
Running test case 5/10...
Running test case 6/10...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1973.88ms

API error or rate limit. Attempt 1/3
Waiting before retrying...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1139.78ms

API error or rate limit. Attempt 2/3
Waiting before retrying...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 785.27ms

API error or rate limit. Attempt 3/3
Waiting before retrying...
Running test case 7/10...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1341.62ms

API error or rate limit. Attempt 1/3
Waiting before retrying...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1620.68ms

API error or rate limit. Attempt 2/3
Waiting before retrying...
Running test case 8/10...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1746.13ms

API error or rate limit. Attempt 1/3
Waiting before retrying...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 8727.82ms

API error or rate limit. Attempt 2/3
Waiting before retrying...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 835.67ms

API error or rate limit. Attempt 3/3
Waiting before retrying...
Running test case 9/10...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 888.83ms

API error or rate limit. Attempt 1/3
Waiting before retrying...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1088.46ms

API error or rate limit. Attempt 2/3
Waiting before retrying...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1493.14ms

API error or rate limit. Attempt 3/3
Waiting before retrying...
Running test case 10/10...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 861.08ms

API error or rate limit. Attempt 1/3
Waiting before retrying...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 1114.14ms

API error or rate limit. Attempt 2/3
Waiting before retrying...

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.5-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 886.83ms

API error or rate limit. Attempt 3/3
Waiting before retrying...

,Question Type,Query,Reference Answer,Generated Answer,Response Time (sec)
0,In-dataset,What should I do if someone is choking?,Encourage coughing if possible. If the person ...,* Encourage the person to cough if they can....,4.73
1,In-dataset,What should I do if someone has a burn?,"Cool the burn with running water, cover it wit...",* Stop the burning process; this might mean ...,4.02
2,In-dataset,How can I stop bleeding?,Apply firm pressure with a clean cloth or band...,* Put on disposable gloves if you have them....,5.57
3,In-dataset,How can I perform CPR?,"Call emergency services, start chest compressi...",* Ensure the person is on a firm surface.\n*...,4.30
4,In-dataset,What should I do for a nosebleed?,"Sit upright, lean forward, pinch the soft part...",* Sit upright and lean slightly forward.\n* ...,2.45
5,Out-of-dataset,"My friend fainted suddenly, what should I do?","Lay the person down, raise their legs, check b...",ERROR: API generation failed.,93.93
6,Out-of-dataset,"A person is shaking and having a seizure, how ...","Keep the person safe, move harmful objects awa...",* Clear the area of sharp objects to protect...,66.65
7,Out-of-dataset,Someone is overheated and confused after being...,"Move the person to a cool place, cool their bo...",ERROR: API generation failed.,101.35
8,Out-of-dataset,Someone twisted their ankle and it is swelling...,"Rest the injured ankle, apply ice wrapped in c...",ERROR: API generation failed.,93.52
9,Out-of-dataset,What should I do if someone may be having a he...,"Call emergency services immediately, keep the ...",ERROR: API generation failed.,92.92

In [ ]:
# =========================================================
# RAG SYSTEM EVALUATION - PART 2
# BERTScore Evaluation
# =========================================================

!pip install bert-score

from bert_score import score

references = eval_df["Reference Answer"].tolist()
candidates = eval_df["Generated Answer"].tolist()

P, R, F1 = score(
    candidates,
    references,
    lang="en",
    verbose=True
)

eval_df["BERTScore Precision"] = P.tolist()
eval_df["BERTScore Recall"] = R.tolist()
eval_df["BERTScore F1"] = F1.tolist()

eval_df[[
    "Question Type",
    "Query",
    "BERTScore Precision",
    "BERTScore Recall",
    "BERTScore F1"
]]

Requirement already satisfied: bert-score in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.10.0+cpu)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.2.2)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (5.0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (4.67.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert-score) (3.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bert-score) (26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2026.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (1.11.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2026.4.22)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert-score) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert-score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.1.2)

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

RobertaModel LOAD REPORT from: roberta-large
Key                             | Status     |
--------------------------------+------------+-
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
pooler.dense.weight             | MISSING    |
pooler.dense.bias               | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

calculating scores...
computing bert embedding.

  0%|          | 0/1 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/1 [00:00<?, ?it/s]

done in 20.94 seconds, 0.48 sentences/sec

,Question Type,Query,BERTScore Precision,BERTScore Recall,BERTScore F1
0,In-dataset,What should I do if someone is choking?,0.861179,0.933247,0.895765
1,In-dataset,What should I do if someone has a burn?,0.831573,0.913842,0.870769
2,In-dataset,How can I stop bleeding?,0.838441,0.885864,0.861500
3,In-dataset,How can I perform CPR?,0.833463,0.913554,0.871673
4,In-dataset,What should I do for a nosebleed?,0.855157,0.939955,0.895553
5,Out-of-dataset,"My friend fainted suddenly, what should I do?",0.858828,0.822997,0.840531
6,Out-of-dataset,"A person is shaking and having a seizure, how ...",0.856017,0.906571,0.880569
7,Out-of-dataset,Someone is overheated and confused after being...,0.856838,0.824074,0.840136
8,Out-of-dataset,Someone twisted their ankle and it is swelling...,0.858784,0.805974,0.831541
9,Out-of-dataset,What should I do if someone may be having a he...,0.859693,0.825288,0.842139

In [ ]:
# =========================================================
# RAG SYSTEM EVALUATION - PART 3
# ROUGE Evaluation + Summary
# =========================================================

!pip install rouge-score

from rouge_score import rouge_scorer
import pandas as pd

scorer = rouge_scorer.RougeScorer(
    ["rouge1", "rouge2", "rougeL"],
    use_stemmer=True
)

rouge1_scores = []
rouge2_scores = []
rougeL_scores = []

for ref, gen in zip(references, candidates):
    scores = scorer.score(ref, gen)
    rouge1_scores.append(scores["rouge1"].fmeasure)
    rouge2_scores.append(scores["rouge2"].fmeasure)
    rougeL_scores.append(scores["rougeL"].fmeasure)

eval_df["ROUGE-1"] = rouge1_scores
eval_df["ROUGE-2"] = rouge2_scores
eval_df["ROUGE-L"] = rougeL_scores

summary_df = pd.DataFrame({
    "Metric": [
        "BERTScore Precision",
        "BERTScore Recall",
        "BERTScore F1",
        "ROUGE-1",
        "ROUGE-2",
        "ROUGE-L",
        "Average Response Time"
    ],
    "Score": [
        eval_df["BERTScore Precision"].mean(),
        eval_df["BERTScore Recall"].mean(),
        eval_df["BERTScore F1"].mean(),
        eval_df["ROUGE-1"].mean(),
        eval_df["ROUGE-2"].mean(),
        eval_df["ROUGE-L"].mean(),
        eval_df["Response Time (sec)"].mean()
    ]
})

display(eval_df)
display(summary_df)

Requirement already satisfied: rouge-score in /usr/local/lib/python3.12/dist-packages (0.1.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge-score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (4.67.3)

,Question Type,Query,Reference Answer,Generated Answer,Response Time (sec),BERTScore Precision,BERTScore Recall,BERTScore F1,ROUGE-1,ROUGE-2,ROUGE-L
0,In-dataset,What should I do if someone is choking?,Encourage coughing if possible. If the person ...,* Encourage the person to cough if they can....,4.73,0.861179,0.933247,0.895765,0.383562,0.140845,0.301370
1,In-dataset,What should I do if someone has a burn?,"Cool the burn with running water, cover it wit...",* Stop the burning process; this might mean ...,4.02,0.831573,0.913842,0.870769,0.197183,0.057143,0.154930
2,In-dataset,How can I stop bleeding?,Apply firm pressure with a clean cloth or band...,* Put on disposable gloves if you have them....,5.57,0.838441,0.885864,0.861500,0.293333,0.027397,0.160000
3,In-dataset,How can I perform CPR?,"Call emergency services, start chest compressi...",* Ensure the person is on a firm surface.\n*...,4.30,0.833463,0.913554,0.871673,0.282828,0.123711,0.161616
4,In-dataset,What should I do for a nosebleed?,"Sit upright, lean forward, pinch the soft part...",* Sit upright and lean slightly forward.\n* ...,2.45,0.855157,0.939955,0.895553,0.491803,0.203390,0.459016
5,Out-of-dataset,"My friend fainted suddenly, what should I do?","Lay the person down, raise their legs, check b...",ERROR: API generation failed.,93.93,0.858828,0.822997,0.840531,0.000000,0.000000,0.000000
6,Out-of-dataset,"A person is shaking and having a seizure, how ...","Keep the person safe, move harmful objects awa...",* Clear the area of sharp objects to protect...,66.65,0.856017,0.906571,0.880569,0.303797,0.155844,0.253165
7,Out-of-dataset,Someone is overheated and confused after being...,"Move the person to a cool place, cool their bo...",ERROR: API generation failed.,101.35,0.856838,0.824074,0.840136,0.000000,0.000000,0.000000
8,Out-of-dataset,Someone twisted their ankle and it is swelling...,"Rest the injured ankle, apply ice wrapped in c...",ERROR: API generation failed.,93.52,0.858784,0.805974,0.831541,0.000000,0.000000,0.000000
9,Out-of-dataset,What should I do if someone may be having a he...,"Call emergency services immediately, keep the ...",ERROR: API generation failed.,92.92,0.859693,0.825288,0.842139,0.000000,0.000000,0.000000

                  Metric      Score
0    BERTScore Precision   0.850997
1       BERTScore Recall   0.877137
2           BERTScore F1   0.863018
3                ROUGE-1   0.195251
4                ROUGE-2   0.070833
5                ROUGE-L   0.149010
6  Average Response Time  46.944000

### **Ui using streamlit**

In [ ]:
!pip install streamlit pyngrok chromadb sentence-transformers google-generativeai

Collecting streamlit
  Downloading streamlit-1.57.0-py3-none-any.whl.metadata (9.6 kB)
Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: chromadb in /usr/local/lib/python3.12/dist-packages (1.5.9)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: google-generativeai in /usr/local/lib/python3.12/dist-packages (0.8.6)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.3)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.47)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.1)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.46.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.26)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.5.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.14.0)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.3)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.26.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.41.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.41.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.41.1)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.80.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.2)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (35.0.0)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.8)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.30.3)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.194.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.47.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.27.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.20.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.13)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core->google-generativeai) (1.74.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.41.1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.41.1)
Requirement already satisfied: opentelemetry-proto==1.41.1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.41.1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.62b1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.62b1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.20.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (0.31.2)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (0.3.1)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.3.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Downloading streamlit-1.57.0-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 78.0 MB/s eta 0:00:00
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 73.4 MB/s eta 0:00:00
Installing collected packages: pyngrok, pydeck, streamlit
Successfully installed pydeck-0.9.2 pyngrok-8.1.2 streamlit-1.57.0

In [ ]:
%%writefile app.py

import streamlit as st
import pandas as pd
import chromadb
from sentence_transformers import SentenceTransformer
import google.generativeai as genai

# =========================
# Gemini API
# =========================
genai.configure(api_key="AIzaSyDsyHmoPE3YLjLhgTMoW89IaCCVbBRparM")
model = genai.GenerativeModel("models/gemini-2.5-flash")

# =========================
# Load Dataset
# =========================
df = pd.read_csv('/content/merged_data.csv')

if 'Unnamed: 0' in df.columns:
    df = df.drop(columns=['Unnamed: 0'])

df = df.dropna()

documents = []
for i, row in df.iterrows():
    text = f"Question: {row['question']}\nAnswer: {row['answer']}"
    documents.append(text)

# =========================
# Embeddings + ChromaDB
# =========================
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = embedding_model.encode(documents)

client = chromadb.Client()

try:
    collection = client.create_collection(name="first_aid_collection")
except:
    collection = client.get_collection(name="first_aid_collection")

for i, doc in enumerate(documents):
    try:
        collection.add(
            documents=[doc],
            embeddings=[embeddings[i].tolist()],
            ids=[str(i)]
        )
    except:
        pass

# =========================
# Page Config
# =========================
st.set_page_config(
    page_title="AidBot AI",
    page_icon="🚑",
    layout="wide"
)

# =========================
# CSS
# =========================
st.markdown("""
<style>
.stApp {
    background: radial-gradient(circle at top left, #7f1d1d 0%, #111827 38%, #020617 100%);
    color: white;
}

.block-container {
    padding-top: 2rem;
    padding-bottom: 2rem;
}

.hero {
    background: linear-gradient(135deg, rgba(220,38,38,0.95), rgba(127,29,29,0.95));
    padding: 45px;
    border-radius: 28px;
    text-align: center;
    color: white;
    box-shadow: 0px 12px 35px rgba(0,0,0,0.35);
    margin-bottom: 28px;
    border: 1px solid rgba(255,255,255,0.18);
}

.hero h1 {
    font-size: 58px;
    margin-bottom: 8px;
    font-weight: 900;
}

.hero p {
    font-size: 22px;
    color: #fee2e2;
}

.badges {
    display: flex;
    justify-content: center;
    gap: 14px;
    flex-wrap: wrap;
    margin-top: 22px;
}

.badge {
    background: rgba(255,255,255,0.18);
    padding: 10px 18px;
    border-radius: 999px;
    font-weight: 700;
    border: 1px solid rgba(255,255,255,0.25);
}

.warning-box {
    background: #fff7ed;
    color: #7c2d12;
    padding: 18px 22px;
    border-radius: 18px;
    border-left: 7px solid #f97316;
    font-size: 17px;
    margin-bottom: 24px;
    box-shadow: 0px 8px 20px rgba(0,0,0,0.18);
}

.card {
    background: rgba(255,255,255,0.96);
    color: #111827;
    padding: 24px;
    border-radius: 22px;
    box-shadow: 0px 10px 28px rgba(0,0,0,0.25);
    margin-bottom: 20px;
}

.answer-box {
    background: #ffffff;
    color: #111827;
    padding: 28px;
    border-radius: 24px;
    border-left: 8px solid #dc2626;
    box-shadow: 0px 12px 30px rgba(0,0,0,0.30);
    margin-top: 25px;
}

.context-box {
    background: #f8fafc;
    color: #111827;
    padding: 22px;
    border-radius: 20px;
    border-left: 7px solid #64748b;
    margin-top: 20px;
    font-size: 14px;
}

.metric-card {
    background: rgba(255,255,255,0.12);
    padding: 18px;
    border-radius: 18px;
    text-align: center;
    color: white;
    border: 1px solid rgba(255,255,255,0.18);
}

div.stButton > button {
    background: linear-gradient(90deg, #dc2626, #ef4444);
    color: white;
    border-radius: 14px;
    height: 52px;
    font-size: 18px;
    font-weight: 800;
    border: none;
    box-shadow: 0px 6px 18px rgba(220,38,38,0.35);
}

div.stButton > button:hover {
    background: linear-gradient(90deg, #991b1b, #dc2626);
    color: white;
    transform: scale(1.01);
}

.stTextInput label, .stCheckbox label {
    color: white !important;
    font-weight: 700;
}

[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #111827, #7f1d1d);
}

[data-testid="stSidebar"] * {
    color: white;
}
</style>
""", unsafe_allow_html=True)

# =========================
# Sidebar
# =========================
with st.sidebar:
    st.title("🚑 AidBot AI")
    st.markdown("### Project Info")
    st.write("**System Type:** RAG Chatbot")
    st.write("**Domain:** Healthcare / First Aid")
    st.write("**Embedding Model:** all-MiniLM-L6-v2")
    st.write("**Vector Store:** ChromaDB")
    st.write("**Generative Model:** Gemini")

    st.markdown("---")
    st.markdown("### Suggested Questions")
    st.write("• What should I do if someone is choking?")
    st.write("• What should I do if someone has a burn?")
    st.write("• How can I help someone who is fainting?")
    st.write("• What should I do during a seizure?")
    st.write("• How to stop bleeding?")

# =========================
# Hero
# =========================
st.markdown("""
<div class="hero">
    <h1>🚑 AidBot AI</h1>
    <p>A Retrieval-Augmented First Aid Assistant</p>
    <div class="badges">
        <div class="badge">RAG System</div>
        <div class="badge">First Aid Guidance</div>
        <div class="badge">Gemini-Powered</div>
        <div class="badge">ChromaDB Retrieval</div>
    </div>
</div>
""", unsafe_allow_html=True)

# =========================
# Metrics
# =========================
col1, col2, col3 = st.columns(3)

with col1:
    st.markdown('<div class="metric-card"><h3>345</h3><p>First-Aid Documents</p></div>', unsafe_allow_html=True)

with col2:
    st.markdown('<div class="metric-card"><h3>384</h3><p>Embedding Dimensions</p></div>', unsafe_allow_html=True)

with col3:
    st.markdown('<div class="metric-card"><h3>Top-3</h3><p>Retrieved Contexts</p></div>', unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# =========================
# Warning
# =========================
st.markdown("""
<div class="warning-box">
⚠️ <b>Important Safety Notice:</b> This assistant provides educational first-aid guidance only.
For serious or life-threatening situations, contact emergency services immediately.
</div>
""", unsafe_allow_html=True)

# =========================
# Main Input Card
# =========================
st.markdown('<div class="card">', unsafe_allow_html=True)

st.subheader("Ask a First-Aid Question")

query = st.text_input(
    "Enter your question:",
    placeholder="Example: What should I do if someone is choking?"
)

show_context = st.checkbox("Show retrieved context for explanation/demo")

generate = st.button("🚨 Get First-Aid Guidance")

st.markdown('</div>', unsafe_allow_html=True)

# =========================
# RAG Pipeline
# =========================
if generate:

    if query.strip() == "":
        st.warning("Please enter a question first.")

    else:
        with st.spinner("Retrieving first-aid knowledge and generating response..."):

            query_embedding = embedding_model.encode([query])[0]

            results = collection.query(
                query_embeddings=[query_embedding.tolist()],
                n_results=3
            )

            retrieved_docs = results['documents'][0]
            context = "\n\n".join(retrieved_docs)

            prompt = f"""
You are a helpful AI first-aid assistant.

Use ONLY the retrieved context below to answer the user's question.

Provide:
- Clear first-aid steps
- Very concise answer
- Maximum 5 bullet points
- Safety advice when necessary
- Remind the user to contact emergency services in serious situations

Retrieved Context:
{context}

User Question:
{query}
"""

            response = model.generate_content(prompt)

        st.markdown('<div class="answer-box">', unsafe_allow_html=True)
        st.subheader("🩺 AI First-Aid Guidance")
        st.write(response.text)
        st.markdown('</div>', unsafe_allow_html=True)

        if show_context:
            st.markdown('<div class="context-box">', unsafe_allow_html=True)
            st.subheader("📌 Retrieved Context")
            st.write(context)
            st.markdown('</div>', unsafe_allow_html=True)

st.markdown("""
<br>
<center style="color:#cbd5e1;">
Built as a Retrieval-Augmented Generation prototype for educational first-aid assistance.
</center>
""", unsafe_allow_html=True)

Writing app.py

In [ ]:
!streamlit run app.py &>/content/logs.txt &

!wget -q -O - ipv4.icanhazip.com

!yes | npx cloudflared tunnel --url http://localhost:8501

136.107.150.187
⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋2026-05-14T16:12:56Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-05-14T16:12:56Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-05-14T16:12:59Z INF +--------------------------------------------------------------------------------------------+
2026-05-14T16:12:59Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-05-14T16:12:59Z INF |  https://lips-ships-filed-payment.trycloudflare.com                                        |
2026-05-14T16:12:59Z INF +--------------------------------------------------------------------------------------------+
2026-05-14T16:12:59Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-05-14T16:12:59Z INF Version 2026.5.0 (Checksum 0095e46fdc88855d801c4d304cb1f5dd4bd656116c47ab94c2ad0ae7cda1c7ec)
2026-05-14T16:12:59Z INF GOOS: linux, GOVersion: go1.26.2, GoArch: amd64
2026-05-14T16:12:59Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8501]
2026-05-14T16:12:59Z INF cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configure-tunnels/local-management/as-a-service/
2026-05-14T16:12:59Z INF Generated Connector ID: d6696301-f2e1-44a6-aa77-f8a4143d0e0f
2026-05-14T16:12:59Z INF Initial protocol quic
2026-05-14T16:12:59Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-05-14T16:12:59Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-05-14T16:13:00Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-05-14T16:13:00Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-05-14T16:13:00Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-05-14T16:13:00Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.192.57
2026/05/14 16:13:00 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-05-14T16:13:00Z INF Registered tunnel connection connIndex=0 connection=ec8e9054-a21a-4453-b15a-d7940e9326e0 event=0 ip=198.41.192.57 location=iad17 protocol=quic
2026-05-14T16:19:02Z INF Initiating graceful shutdown due to signal interrupt ...
2026-05-14T16:19:02Z ERR failed to run the datagram handler error="context canceled" connIndex=0 event=0 ip=198.41.192.57
2026-05-14T16:19:02Z ERR failed to serve tunnel connection error="accept stream listener encountered a failure while serving" connIndex=0 event=0 ip=198.41.192.57
2026-05-14T16:19:02Z ERR Serve tunnel error error="accept stream listener encountered a failure while serving" connIndex=0 event=0 ip=198.41.192.57
2026-05-14T16:19:02Z INF Retrying connection in up to 1s connIndex=0 event=0 ip=198.41.192.57
2026-05-14T16:19:02Z ERR Connection terminated connIndex=0
2026-05-14T16:19:02Z ERR no more connections active and exiting
2026-05-14T16:19:02Z INF Tunnel server stopped
2026-05-14T16:19:02Z INF Metrics server stopped
^C